---

- name: Bootstrap
  gather_facts: true
  hosts: clients
  vars:
    # This is lab setup
    ansible_user: root
    ansible_ssh_password: "{{ bootstrap_root_password }}"
  roles:
    - role: bootstrap

- name: Install user stuff
  gather_facts: true
  hosts: fedora
  vars:
    ansible_user: "{{ bootstrap_user | default('sebbe') }}"
    ansible_become_password: "{{ bootstrap_user_password }}"

  roles:
    - role: client-setup
