---
client_setup_homebrew_url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
client_setup_fisher_url: "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"
client_setup_user: sebbe
client_setup_elephant_version: "2.17.1"
client_setup_elephant_plugins:
  - 1password
  - bluetooth
  - clipboard
  - desktopapplications
  - files
  - menus
  - runner
  - symbols
  - unicode
  - windows
client_setup_walker_version: "2.12.2"
client_setup_copr:
  - host: "copr.fedorainfracloud.org"
    name: scottames/ghostty
    state: enabled
  - host: "copr.fedorainfracloud.org"
    name: che/nerd-fonts
    state: enabled
  - host: "copr.fedorainfracloud.org"
    name: solopasha/hyprland
    state: enabled
client_setup_wm: "sway"
