---
- name: Git clone tpm tmux manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "/home/{{ client_setup_user }}/.config/tmux/plugins/tpm"
    version: master
  tags:
    - setup
    - tmux

- name: Git clone tmux cattppuccin
  ansible.builtin.git:
    repo: https://github.com/catppuccin/tmux
    dest: "/home/{{ client_setup_user }}/.config/tmux/plugins/catppuccin/tmux"
    version: "v2.1.3"
  tags:
    - setup
    - tmux
